---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# evdce

<!-- badges: start -->

<!-- badges: end -->

This is the repository for scripts and data accompanying the book "Environmental Valuation with Discrete Choice Experiments".

## Authors

1.  Petr Mariel, University of the Basque Country, UPV/EHU

2.  Danny Campbell, University of Stirling

3.  Erlend Dancke Sandorf, Norwegian University of Life Sciences, NMBU

4.   Jürgen Meyerhoff, Berlin School of Economics and Law

5.  Ainhoa Vega-Bayo, University of the Basque Country, UPV/EHU

6.  Rebecca Blevins, Basque Centre for Climate Change BC3

All authors are members of the [ENVECHO](https://envecho.com/ "A scientific network of researchers using Discrete Choice Modelling in the field of environmental valuation.") network.

## Reference

Mariel. P., Campbell, D., Sandorf, E. D., Meyerhoff, J., Vega-Bayo, A. & Blevins, R., 2025, Environmental Valuation with Discrete Choice Experiments, Springer

## Acknowledgements

We are grateful to all members of [ENVECHO](https://envecho.com/ "A scientific network of researchers using Discrete Choice Modelling in the field of environmental valuation.") who have contributed to the development of the book.
